extends RefCounted
class_name StageVisualProfile

const STAGE_ACTOR_SCALE := 1.28
const PLAYER_STAGE_ACTOR_SCALE := 1.28
const NPC_STAGE_ACTOR_SCALE := 1.44
const STAGE_SIDE_VIEW_ENTITY_HEIGHT := 126.0
const STAGE_SIDE_VIEW_PLAYER_WIDTH := 108.0
const STAGE_SIDE_VIEW_NPC_BASE_HEIGHT := 126.0
const STAGE_SIDE_VIEW_NPC_BASE_WIDTH := 86.0
const STAGE_SIDE_VIEW_NPC_MASTER_HEIGHT := 156.0
const STAGE_SIDE_VIEW_NPC_MASTER_WIDTH := 94.0
const STAGE_SIDE_VIEW_NPC_ENEMY_HEIGHT := 152.0
const STAGE_SIDE_VIEW_NPC_ENEMY_WIDTH := 92.0
const STAGE_SIDE_VIEW_NPC_STAGE_BASE_WIDTH := 108.0
const STAGE_SIDE_VIEW_NPC_STAGE_MASTER_WIDTH := 120.0
const STAGE_SIDE_VIEW_NPC_STAGE_ENEMY_WIDTH := 118.0
const STAGE_SPRITE_MIN_SCALE := 1.30
const STAGE_SPRITE_MAX_SCALE := 1.86

const PLAYER_STAGE_SCALE_BIAS := 1.0
const NPC_MASTER_STAGE_SCALE_BIAS := 1.09
const NPC_ENEMY_STAGE_SCALE_BIAS := 1.11
const NPC_STAGE_SCALE_BIAS := 1.0

const WORLD_MAP_TILE_TRANSITION_DECIMATION := 4
const WORLD_MAP_TILE_DETAIL_DECIMATION := 3
const WORLD_MAP_BUILDING_OVERLAY_DECIMATION := 5

const LOCAL_MAP_TILE_DETAIL_DECIMATION := 3
const LOCAL_MAP_TILE_TRANSITION_DECIMATION := 4
const LOCAL_MAP_BUILDING_TILE_DECIMATION := 2

const WORLD_PAINTERLY_STROKE_COUNT := 62
const WORLD_PAINTERLY_STROKE_ALPHA := 0.072
const WORLD_PAINTERLY_BLOB_COUNT := 40
const WORLD_PAINTERLY_BLOB_ALPHA := 0.060
const WORLD_BUILDING_EDGE_DECIMATION := 2
const WORLD_BUILDING_EDGE_ALPHA := 0.22
const WORLD_BUILDING_EDGE_WIDTH := 1.6
const WORLD_BUILDING_EDGE_NOISE := 0.16
const WORLD_BUILDING_SURFACE_STROKE_COUNT := 8
const WORLD_BUILDING_SURFACE_DOT_COUNT := 7
const WORLD_BUILDING_SURFACE_ALPHA := 0.11
const WORLD_BUILDING_SURFACE_SEED_BASE := 700
const WORLD_BUILDING_SURFACE_LINE_JITTER := 2.8
const WORLD_BUILDING_SURFACE_NOISE_SCALE := 0.10
const WORLD_BUILDING_FACADE_PILLAR_COUNT := 5
const WORLD_BUILDING_FACADE_WINDOW_ROWS := 6
const WORLD_BUILDING_FACADE_WINDOW_COLUMNS := 6
const WORLD_BUILDING_FACADE_WINDOW_ALPHA := 0.12
const WORLD_BUILDING_FACADE_SHADOW_ALPHA := 0.22
const WORLD_BUILDING_FACADE_SEED_BASE := 770
const WORLD_BUILDING_FACADE_LINE_JITTER := 3.0
const WORLD_BUILDING_FACADE_NOISE_SCALE := 0.10

const LOCAL_PAINTERLY_STROKE_COUNT := 42
const LOCAL_PAINTERLY_STROKE_ALPHA := 0.065
const LOCAL_PAINTERLY_DOT_COUNT := 72
const LOCAL_PAINTERLY_DOT_ALPHA := 0.038
const LOCAL_BUILDING_EDGE_DECIMATION := 2
const LOCAL_BUILDING_EDGE_ALPHA := 0.24
const LOCAL_BUILDING_EDGE_WIDTH := 1.35
const LOCAL_BUILDING_EDGE_NOISE := 0.22
const LOCAL_BUILDING_SURFACE_STROKE_COUNT := 8
const LOCAL_BUILDING_SURFACE_DOT_COUNT := 8
const LOCAL_BUILDING_SURFACE_ALPHA := 0.10
const LOCAL_BUILDING_SURFACE_SEED_BASE := 620
const LOCAL_BUILDING_SURFACE_LINE_JITTER := 2.8
const LOCAL_BUILDING_SURFACE_NOISE_SCALE := 0.10
const LOCAL_BUILDING_FACADE_PILLAR_COUNT := 5
const LOCAL_BUILDING_FACADE_WINDOW_ROWS := 5
const LOCAL_BUILDING_FACADE_WINDOW_COLUMNS := 6
const LOCAL_BUILDING_FACADE_WINDOW_ALPHA := 0.14
const LOCAL_BUILDING_FACADE_SHADOW_ALPHA := 0.2
const LOCAL_BUILDING_FACADE_SEED_BASE := 840
const LOCAL_BUILDING_FACADE_LINE_JITTER := 2.4
const LOCAL_BUILDING_FACADE_NOISE_SCALE := 0.09

static func tile_random(ix: int, iy: int, seed: int) -> int:
	var value := (ix * 374761393 + iy * 668265263) ^ (seed + 31)
	value = (value ^ (value >> 13)) * 1274126177
	value = value ^ (value >> 16)
	value = value & 0x7fffffff
	if value < 0:
		value = -value
	return value

static func tile_noise(ix: int, iy: int, seed: int) -> float:
	return float(tile_random(ix, iy, seed) % 1000) / 1000.0

static func tile_wave(ix: int, iy: int, seed: int) -> float:
	var angle := tile_noise(ix, iy, seed) * TAU
	return (sin(angle) + 1.0) * 0.5

static func tile_offset(ix: int, iy: int, seed: int, strength: float) -> float:
	return (tile_noise(ix, iy, seed) - 0.5) * strength
