from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "data" / "npcs.json"
TARGET = ROOT / "godot_project" / "data" / "npcs.json"
ITEMS = ROOT / "godot_project" / "data" / "items.json"


POSITIONS: dict[str, tuple[int, int]] = {
    "平阿四": (28, 15),
    "店小二": (29, 15),
    "阎商": (39, 22),
    "葛朗台": (47, 22),
    "阿青": (27, 17),
    "厨师": (29, 16),
    "屠夫": (27, 15),
    "卖花女": (41, 27),
    "小商贩": (31, 17),
    "平一指": (51, 26),
    "何铁手": (50, 23),
    "何喜": (56, 16),
    "小裁缝": (22, 59),
    "何裁缝": (24, 59),
    "捕快": (32, 16),
    "巡捕": (33, 17),
    "衙役": (32, 18),
    "老夫子": (28, 18),
    "村长": (30, 16),
    "老婆婆": (27, 18),
    "妇人": (29, 18),
    "公子哥": (46, 27),
    "书童": (45, 26),
    "小童": (31, 18),
    "过路人": (52, 28),
    "茅十七": (55, 27),
    "韦扬": (24, 10),
    "简明": (21, 9),
    "简杰": (22, 12),
    "简英": (27, 12),
    "鲍振": (26, 9),
    "武师教头": (20, 12),
    "春花娘": (27, 10),
    "护院武师": (24, 13),
    "清照": (88, 49),
    "红拂女": (85, 48),
    "公孙大娘": (86, 51),
    "青红": (90, 48),
    "绿珠": (85, 52),
    "雪涛": (91, 52),
    "隐娘": (88, 47),
    "王辞": (90, 50),
    "于红儒": (40, 36),
    "方长老": (37, 35),
    "韩长老": (43, 35),
    "楚红灯": (37, 38),
    "崇儿": (43, 38),
    "唐四儿": (40, 39),
    "白衣教众": (36, 37),
    "红衣教众": (43, 37),
    "钟央": (81, 36),
    "十三卫": (78, 35),
    "美奈子": (78, 38),
    "藤王": (83, 35),
    "游敬": (84, 37),
    "天井": (80, 39),
    "孙三": (83, 39),
    "浪人甲": (74, 35),
    "清虚道人": (67, 34),
    "古松道人": (64, 33),
    "仓月道人": (70, 33),
    "采药道人": (64, 36),
    "知客道人": (70, 36),
    "迎客道童": (66, 37),
    "明月": (65, 35),
    "清风": (69, 37),
    "白瑞德": (48, 11),
    "史婆婆": (45, 9),
    "万剑": (50, 9),
    "万刃": (52, 12),
    "万重": (45, 12),
    "万一": (47, 10),
    "阿秀": (49, 12),
    "雪千柔": (52, 10),
    "流氓": (35, 16),
    "流氓头": (37, 18),
    "独角大盗": (59, 36),
    "采花大盗": (40, 20),
    "黑衣大盗": (64, 34),
    "土匪甲": (56, 12),
    "土匪头目": (58, 15),
    "雪豹": (50, 6),
    "大侠": (34, 17),
    "道德和尚": (30, 14),
    "李白": (31, 15),
    "神秘人": (34, 21),
    "绣花女": (88, 54),
    "魔化和尚": (55, 39),
}

FIELD_ORDER = (
    "id",
    "name",
    "npc_type",
    "faction",
    "personality",
    "description",
    "level",
    "hp",
    "max_hp",
    "mp",
    "max_mp",
    "attack",
    "defense",
    "damage",
    "money",
    "exp_reward",
    "sell_items",
    "pos_x",
    "pos_y",
    "is_master",
    "teach_skills",
    "has_quests",
)

STAT_OVERRIDES: dict[str, dict[str, int]] = {
    "神秘人": {"level": 22, "hp": 520, "max_hp": 520, "attack": 34, "defense": 18, "damage": 18, "money": 500, "exp_reward": 260},
    "绣花女": {"level": 28, "hp": 760, "max_hp": 760, "attack": 44, "defense": 24, "damage": 24, "money": 520, "exp_reward": 380},
    "魔化和尚": {"level": 32, "hp": 920, "max_hp": 920, "attack": 52, "defense": 30, "damage": 30, "money": 600, "exp_reward": 520},
}

TYPE_OVERRIDES = {
    "店小二": "trader",
}

SELL_OVERRIDES = {
    "店小二": ["item_baozi", "item_wine"],
}

EXTRA_NPCS = [
    {
        "id": 200,
        "name": "铁匠",
        "npc_type": "trader",
        "faction": "none",
        "personality": "沉稳粗粝",
        "description": "镇上铁匠，出售入门兵器和护具",
        "level": 8,
        "hp": 180,
        "max_hp": 180,
        "mp": 30,
        "max_mp": 30,
        "attack": 18,
        "defense": 12,
        "damage": 8,
        "money": 600,
        "exp_reward": 20,
        "sell_items": ["item_sword", "item_blade", "item_cloth", "item_fine_cloth"],
        "pos_x": 32,
        "pos_y": 15,
        "has_quests": False,
    },
    {
        "id": 301,
        "name": "苏梦瑶",
        "npc_type": "normal",
        "faction": "flower",
        "personality": "活泼坚韧",
        "description": "洛阳苏家遗孤，身怀花间剑法线索，正在追查旧宅大火真相",
        "level": 12,
        "hp": 260,
        "max_hp": 260,
        "mp": 140,
        "max_mp": 140,
        "attack": 26,
        "defense": 14,
        "damage": 12,
        "money": 120,
        "exp_reward": 80,
        "pos_x": 42,
        "pos_y": 24,
        "has_quests": True,
        "teach_skills": ["kf_huafei"],
    },
    {
        "id": 302,
        "name": "陈天行",
        "npc_type": "normal",
        "faction": "none",
        "personality": "冷静正直",
        "description": "长安说书人，真实身份疑似暗影司叛逃密探",
        "level": 18,
        "hp": 360,
        "max_hp": 360,
        "mp": 180,
        "max_mp": 180,
        "attack": 32,
        "defense": 18,
        "damage": 16,
        "money": 160,
        "exp_reward": 120,
        "pos_x": 21,
        "pos_y": 34,
        "has_quests": True,
        "teach_skills": ["kf_basic_sword"],
    },
    {
        "id": 303,
        "name": "赵无极",
        "npc_type": "master",
        "faction": "none",
        "personality": "威严多疑",
        "description": "洛阳武林盟执事，表面维持秩序，暗中掌握许多旧案卷宗",
        "level": 24,
        "hp": 520,
        "max_hp": 520,
        "mp": 220,
        "max_mp": 220,
        "attack": 38,
        "defense": 24,
        "damage": 20,
        "money": 500,
        "exp_reward": 180,
        "pos_x": 48,
        "pos_y": 21,
        "has_quests": True,
        "teach_skills": ["kf_basic_parry"],
    },
    {
        "id": 304,
        "name": "玄机子",
        "npc_type": "master",
        "faction": "bagua",
        "personality": "孤僻正直",
        "description": "八卦门掌门，精通奇门阵法，追寻上古八卦图真本",
        "level": 36,
        "hp": 860,
        "max_hp": 860,
        "mp": 420,
        "max_mp": 420,
        "attack": 62,
        "defense": 38,
        "damage": 32,
        "money": 900,
        "exp_reward": 420,
        "pos_x": 24,
        "pos_y": 9,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_bazhen", "kf_hunyuan"],
    },
    {
        "id": 305,
        "name": "花如玉",
        "npc_type": "master",
        "faction": "flower",
        "personality": "冷淡细致",
        "description": "花间派长老，擅长易容、剑舞与花毒，知晓苏家旧事",
        "level": 32,
        "hp": 720,
        "max_hp": 720,
        "mp": 460,
        "max_mp": 460,
        "attack": 54,
        "defense": 30,
        "damage": 28,
        "money": 780,
        "exp_reward": 360,
        "pos_x": 87,
        "pos_y": 50,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_huatuan", "kf_meihua"],
    },
    {
        "id": 306,
        "name": "烈火",
        "npc_type": "master",
        "faction": "honglian",
        "personality": "暴烈忠义",
        "description": "红莲教护法之首，家仇未雪，行事激烈",
        "level": 34,
        "hp": 900,
        "max_hp": 900,
        "mp": 300,
        "max_mp": 300,
        "attack": 66,
        "defense": 34,
        "damage": 34,
        "money": 700,
        "exp_reward": 390,
        "pos_x": 39,
        "pos_y": 35,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_taizu", "kf_pifeng"],
    },
    {
        "id": 307,
        "name": "蛇王",
        "npc_type": "master",
        "faction": "naja",
        "personality": "阴沉狡黠",
        "description": "那迦派掌门，精通暗杀术和毒术，常在暗处观察江湖局势",
        "level": 38,
        "hp": 780,
        "max_hp": 780,
        "mp": 520,
        "max_mp": 520,
        "attack": 70,
        "defense": 32,
        "damage": 36,
        "money": 880,
        "exp_reward": 450,
        "pos_x": 81,
        "pos_y": 35,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_renshu", "kf_yidao"],
    },
    {
        "id": 308,
        "name": "太极真人",
        "npc_type": "master",
        "faction": "taiji",
        "personality": "温和沉静",
        "description": "太极门掌门，武林中德高望重的道门宗师",
        "level": 40,
        "hp": 920,
        "max_hp": 920,
        "mp": 560,
        "max_mp": 560,
        "attack": 62,
        "defense": 46,
        "damage": 32,
        "money": 960,
        "exp_reward": 470,
        "pos_x": 67,
        "pos_y": 33,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_taiji_fist", "kf_taiji_force"],
    },
    {
        "id": 309,
        "name": "冰魄",
        "npc_type": "master",
        "faction": "xueshan",
        "personality": "冷静刚正",
        "description": "雪山派掌门，外冷内正，掌管雪岭寒劲传承",
        "level": 36,
        "hp": 840,
        "max_hp": 840,
        "mp": 480,
        "max_mp": 480,
        "attack": 64,
        "defense": 36,
        "damage": 34,
        "money": 820,
        "exp_reward": 420,
        "pos_x": 48,
        "pos_y": 8,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_xueshan_sword", "kf_xueshang"],
    },
    {
        "id": 310,
        "name": "逍遥子",
        "npc_type": "master",
        "faction": "xiaoyao",
        "personality": "潇洒不羁",
        "description": "逍遥宫掌门，行踪飘忽，懂奇门与北冥一脉旧学",
        "level": 42,
        "hp": 880,
        "max_hp": 880,
        "mp": 680,
        "max_mp": 680,
        "attack": 68,
        "defense": 40,
        "damage": 34,
        "money": 1100,
        "exp_reward": 520,
        "pos_x": 84,
        "pos_y": 63,
        "is_master": True,
        "has_quests": True,
        "teach_skills": ["kf_xiaoyao_you", "kf_beiming"],
    },
]


def ordered_record(record: dict) -> dict:
    return {key: record[key] for key in FIELD_ORDER if key in record}


def main() -> None:
    source_npcs = json.loads(SOURCE.read_text(encoding="utf-8"))
    valid_items = {item["id"] for item in json.loads(ITEMS.read_text(encoding="utf-8"))}
    output = []
    for npc in source_npcs:
        name = npc["name"]
        if name not in POSITIONS:
            continue
        record = {key: npc[key] for key in FIELD_ORDER if key in npc}
        pos_x, pos_y = POSITIONS[name]
        record["pos_x"] = pos_x
        record["pos_y"] = pos_y
        if name in TYPE_OVERRIDES:
            record["npc_type"] = TYPE_OVERRIDES[name]
        if "sell_items" in record:
            record["sell_items"] = [item_id for item_id in record["sell_items"] if item_id in valid_items]
            if not record["sell_items"]:
                del record["sell_items"]
        if name in SELL_OVERRIDES:
            record["sell_items"] = SELL_OVERRIDES[name]
        if name in STAT_OVERRIDES:
            record.update(STAT_OVERRIDES[name])
        output.append(ordered_record(record))
    output.extend(ordered_record(record) for record in EXTRA_NPCS)
    TARGET.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(output)} NPC records to {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
